### PR TITLE
Add demo data into repository

### PR DESCRIPTION
**Pull request by JarettBakerDunn**
I copied the data from https://geodynamics.org/resources/mineos/supportingdocs into the repository in the directory demo-data. I also removed the submodule DEMO folder, I hope that won't make any problems.

### CODE REVIEW

**Comment by ljhwang** [comment]
I recall that we made a decision NOT to include the pdfs so as not to clutter up the repos. The rationale being that it could always be built.   

If we continue to exclude, then the README will need to be updated and perhaps point to https://geodynamics.org/resources/mineos.

**Comment by gassmoeller** [comment]
Thanks for figuring this out, this should fix issues #9 and #11.
But maybe you could put the data into a folder named `DEMO` instead of `demo-data`? That way all old references to the DEMO submodule would continue to work? Or was the data always in a directory called `demo-data`?

**Comment by JarettBakerDunn** [comment]
@gassmoeller  I deleted the DEMO folder because it prevented me from cloning the repository because I couldn't reach the submodule. I don't have much experience with git submodules, so I'm not sure the best way to approach this. It looks like I could unlink the DEMO folder from the submodule and rename the demo-data folder to the original name, which was DEMO. But I don't know if unlinking the directory from the submodule would stop the old references from working.

**Comment by ljhwang** [comment]
I only see the directory DEMO referred to once and that is in the manual.  I don't think you will break anything!

**Review by gassmoeller — APPROVED** [review]
Looks good, this is what I meant with my previous comment. Thanks!

**Pull request merged**
